package com.holopengin.instantjpdict

import com.holopengin.instantjpdict.util.Deinflector
import com.holopengin.instantjpdict.util.KanaOrthography
import com.holopengin.instantjpdict.util.KanaSoundChanges
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

// #81: the historical sound-change normaliser, the class JMdict's entry-local kana
// variants cannot reach (やう->よう, けふ->きょう, 思ふ->思う). The table is the
// committed asset generated by tools/build_kana_sound_changes.py from the two
// Cabinet notices (public domain, 著作権法第13条第2号), so every pair is asserted
// against the file: an edit to the table or a mistyped Kotlin literal fails here
// rather than silently changing lookups.
//
// The normaliser never touches displayed text; the caller searches the raw prefix
// and the #75 form alongside the sound-changed one, which is what makes the pass
// additive by construction. The last test asserts that call-site contract.
class KanaSoundChangesTest {

    private fun table() = KanaSoundChanges.parse(
        TestAssets.assetsFile("variants/kana_sound_changes.txt").readText()
    )

    private fun kana75() = KanaOrthography.parse(
        TestAssets.assetsFile("variants/kana_variants.txt").readText()
    )

    /** The shipped composition: the #75 variant fold first, then the sound changes. */
    private fun normalise(query: String): String =
        KanaSoundChanges.modernise(KanaOrthography.modernise(query))

    @Before
    fun installTheCommittedTables() {
        KanaOrthography.install(kana75())
        KanaSoundChanges.install(table())
    }

    /** Every pair the committed table ships, pinned so an edit is visible. */
    private val shippedHa = mapOf(
        'ふ' to 'う', 'ひ' to 'い', 'へ' to 'え', 'は' to 'わ',
    )
    private val shippedAu = mapOf(
        'か' to 'こ', 'が' to 'ご', 'さ' to 'そ', 'ざ' to 'ぞ', 'た' to 'と', 'だ' to 'ど',
        'な' to 'の', 'は' to 'ほ', 'ば' to 'ぼ', 'ぱ' to 'ぽ', 'ゃ' to 'ょ', 'や' to 'よ',
        'ら' to 'ろ', 'わ' to 'お',
    )
    private val shippedEu = mapOf(
        'け' to "きょ", 'げ' to "ぎょ", 'せ' to "しょ", 'ぜ' to "じょ", 'て' to "ちょ",
        'で' to "じょ", 'ね' to "にょ", 'へ' to "ひょ", 'べ' to "びょ", 'ぺ' to "ぴょ",
        'め' to "みょ", 'れ' to "りょ", 'え' to "よ",
    )

    @Test
    fun parses_the_committed_asset() {
        val lines = TestAssets.assetsFile("variants/kana_sound_changes.txt")
            .readText().lines().count { it.isNotBlank() && !it.startsWith("#") }
        assertEquals(31, lines)
        assertEquals(31, table().size)
    }

    @Test
    fun pins_every_shipped_pair() {
        val t = table()
        for ((variant, canonical) in shippedHa) {
            assertEquals("ha $variant", canonical, t.ha(variant))
        }
        for ((variant, canonical) in shippedAu) {
            assertEquals("au $variant", canonical, t.au(variant))
        }
        for ((variant, canonical) in shippedEu) {
            assertEquals("eu $variant", canonical, t.eu(variant))
        }
    }

    @Test
    fun pins_the_withheld_rows() {
        // Withheld because the measurement says they cost modern lookups and repair
        // nothing on the legacy slice (see the PROVENANCE file and the class doc):
        // あ/ま in the アウ row, ほ in the ハ行 row, and #75's を.
        val t = table()
        assertEquals(null, t.au('あ'))
        assertEquals(null, t.au('ま'))
        assertEquals(null, t.ha('ほ'))
        assertEquals(null, t.au('を'))
        assertEquals(null, t.ha('を'))
        // ...so they fold to themselves even when the context would otherwise fire.
        assertEquals("あう", normalise("あう"))
        assertEquals("まう", normalise("まう"))
        assertEquals("おほ", normalise("おほ"))
        assertEquals("本を読む", normalise("本を読む"))
    }

    @Test
    fun normalises_the_headline_legacy_forms() {
        // The pairs the issue names, through the shipped composition (きやう -> きゃう
        // is #75's 拗音 fold, then ゃ+う -> ょ+う is this table's アウ row).
        assertEquals("よう", normalise("やう"))
        assertEquals("きょう", normalise("きやう"))
        assertEquals("きょう", normalise("けふ"))
        assertEquals("ちょう", normalise("てふ"))
        assertEquals("思う", normalise("思ふ"))
        assertEquals("言う", normalise("言ふ"))
        // The neighbouring sound changes the same rows carry.
        assertEquals("しょう", normalise("しやう"))
        assertEquals("でしょう", normalise("でせう"))
        assertEquals("だろう", normalise("だらう"))
        assertEquals("ありがとう", normalise("ありがたう"))
        assertEquals("とうとし", normalise("たふとし"))
        assertEquals("というのは", normalise("といふのは"))
    }

    @Test
    fun applies_the_ha_row_only_at_the_grammatical_ending() {
        // ハ行四段 終止/連体形: word-final or before a particle.
        assertEquals("思う", normalise("思ふ"))
        assertEquals("思うが", normalise("思ふが"))
        assertEquals("思う人", normalise("思ふ人"))
        assertEquals("云う", normalise("云ふ"))
        // ...and nowhere else: ふ as an ordinary syllable, word-initial ふ, and ふう.
        assertEquals("ふね", normalise("ふね"))
        assertEquals("ふとん", normalise("ふとん"))
        assertEquals("吹く", normalise("吹く"))
        assertEquals("ふうふ", normalise("ふうふ"))
        assertEquals("ふ", normalise("ふ"))
        // 連用形 ひ -> い before て/つ/な.
        assertEquals("思いつ", normalise("思ひつ"))
        assertEquals("戦いながら", normalise("戦ひながら"))
        // ...while a word-initial ひ and the common ひる/ひま are untouched.
        assertEquals("ひる", normalise("ひる"))
        assertEquals("ひま", normalise("ひま"))
        assertEquals("ひが", normalise("ひが"))
        // 連用/仮定/已然 へ -> え.
        assertEquals("数えて", normalise("数へて"))
        assertEquals("言えば", normalise("言へば"))
        assertEquals("添えた", normalise("添へた"))
        assertEquals("へや", normalise("へや"))
        // 未然形 は -> わ before ず/ぬ/む/ば; the particle は never folds.
        assertEquals("言わず", normalise("言はず"))
        assertEquals("思わぬ", normalise("思はぬ"))
        assertEquals("思わば", normalise("思はば"))
        assertEquals("本は", normalise("本は"))
        assertEquals("はな", normalise("はな"))
        assertEquals("はず", normalise("はず"))
    }

    @Test
    fun applies_the_vowel_rows_only_before_u() {
        // アウ -> オウ needs the う; the same a-row kana elsewhere is untouched.
        assertEquals("かき", normalise("かき"))
        assertEquals("こう", normalise("かう"))
        assertEquals("こうして", normalise("かうして"))
        assertEquals("よう", normalise("やう"))
        assertEquals("ようだ", normalise("やうだ"))
        assertEquals("おはよう", normalise("おはやう"))
        // エウ -> ヨウ.
        assertEquals("きょう", normalise("けう"))
        assertEquals("ちょう", normalise("てう"))
        assertEquals("しょう", normalise("せう"))
        // A kanji stem keeps a modern 五段 verb ending out of the rule's reach:
        // the う is preceded by a kanji, not by an a-row kana.
        assertEquals("買う", normalise("買う"))
        assertEquals("会う", normalise("会う"))
    }

    @Test
    fun is_the_identity_on_modern_text() {
        for (modern in listOf("", "あ", "ABC", "日本語", "つくえ", "にっぽん", "がっこう",
                              "コーヒー", "12月", "、。", "つづく", "ちぢむ", "ふね",
                              "コーヒーを飲む", "つくえの上", "クラウン")) {
            assertEquals(modern, normalise(modern))
        }
    }

    @Test
    fun is_deterministic_and_answers_from_the_query_alone() {
        // No page/era/document gate: the answer depends on the queried string, so a
        // word normalises the same inside a sentence as alone.
        val q = "けふ"
        assertEquals(normalise(q), normalise(q))
        assertEquals("きょう", normalise(q))
        assertEquals("きょうは晴れ", normalise("けふは晴れ"))
        assertEquals("。きょう、", normalise("。けふ、"))
        assertEquals("きょう", normalise("けふ"))
    }

    @Test
    fun empty_table_is_the_identity() {
        val t = KanaSoundChanges.parse("")
        assertEquals(0, t.size)
        KanaSoundChanges.install(t)
        assertEquals("けふ", KanaSoundChanges.modernise("けふ"))
        KanaSoundChanges.install(table())
    }

    @Test
    fun parse_skips_malformed_lines_and_keeps_the_first_mapping() {
        val t = KanaSoundChanges.parse(
            """
            # a comment
            ふ	う	ha
            ふ	ひ	ha
            ふう
            う	う	ha
            ふ	う	ha	extra
            け	きょ	eu
            け	きょ	unknown-row
            """.trimIndent() + "\n"
        )
        assertEquals(2, t.size)
        assertEquals('う', t.ha('ふ'))
        assertEquals("きょ", t.eu('け'))
    }

    @Test
    fun the_table_is_kana_only_and_rows_are_known() {
        val text = TestAssets.assetsFile("variants/kana_sound_changes.txt").readText()
        for (raw in text.lineSequence()) {
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) continue
            val parts = line.split('\t')
            assertEquals("3 columns: $line", 3, parts.size)
            assertTrue("single-char variant: $line", parts[0].length == 1)
            val o = parts[0][0].code
            assertTrue("kana variant: $line", o in 0x3041..0x3096 || o in 0x30A1..0x30F6)
            assertTrue("known row: $line", parts[2] in setOf("ha", "au", "eu"))
            val modern = parts[1]
            assertTrue("modern is 1-2 kana: $line",
                modern.length in 1..2 && modern.all { c ->
                    c.code in 0x3041..0x3096 || c.code in 0x30A1..0x30F6
                })
        }
    }

    @Test
    fun the_lookup_adds_the_normalised_form_beside_the_raw_one() {
        // The call-site contract (acceptance criterion 1): the raw query and the #75
        // form stay in the search set and the sound-changed form is one more variant.
        // Nothing here touches displayed text — this only lists queried strings.
        val controller = OcrOverlayStateController()
        val deinflector = Deinflector("{}".reader())
        val (terms, _) = controller.prepareSearchCandidates("きやう", deinflector)
        assertTrue("raw prefix is not searched: $terms", terms.contains("きやう"))
        assertTrue("#75 form is not searched: $terms", terms.contains("きゃう"))
        assertTrue("sound-changed form is not searched: $terms", terms.contains("きょう"))

        val (legacy, _) = controller.prepareSearchCandidates("けふは", deinflector)
        assertTrue("raw prefix is not searched: $legacy", legacy.contains("けふは"))
        assertTrue("sound-changed form is not searched: $legacy", legacy.contains("きょうは"))
    }
}
