package com.holopengin.instantjpdict.util

import android.content.Context
import uniffi.nav_graph_core.ComponentTable as RustComponentTable

/**
 * Kanji component table (KRADFILE) — the visual bridge between what the recogniser
 * *saw* at an unemittable glyph and what a dictionary can *offer* for it (#44).
 *
 * At the `呟` gap the head's top-5 is `咳 咬 啦 哮 眩` — all 口/亠 characters — while
 * `呟` itself decomposes to `亠 口 幺 玄`. Sharing components is what selects the right
 * candidate; a text n-gram cannot separate `呟` from `咲`/`働` in context, but the
 * components can. The table therefore carries both directions:
 *
 *  - [componentsOf] — the decomposition of one character (generation / filtering),
 *  - [kanjiWith] — the inverted index `component -> kanji` (a precomputed posting
 *    list, never a scan of the whole table per call),
 *  - [idfOf] — how *informative* a component is (`ln(kanjiCount / kanjiContaining)`),
 *    so sharing `車` can be weighed against sharing `一`.
 *
 * Since the util-core swap this is a thin facade over the PC `jpdict_core`
 * implementation (`core/src/util/component_table.rs`, exposed through `nav_graph_core`'s
 * UniFFI surface), so the algorithm has one source of truth. The parse rules and the
 * IDF universe are documented there; this class only adapts types (`Char` ↔ `Int` code
 * points, `Long` → `Int`) and keeps the API call sites already use.
 *
 * ## Provenance
 *
 * The asset [ASSET_PATH] is a merged, vendored copy of EDRDG **KRADFILE** and
 * **KRADFILE2** (`http://ftp.edrdg.org/pub/Nihongo/kradzip.zip`; copyright 2001/2007
 * Michael Raine, James Breen and the Electronic Dictionary Research and Development
 * Group; licensed **CC BY-SA 4.0**). 12,156 entries, one line per kanji —
 * `呟:亠 口 幺 玄` — LF endings, sorted by codepoint. The sibling `PROVENANCE.txt`
 * records the entry count, byte size and SHA-256.
 *
 * **The file is generated by `tools/build_component_table.py` and must never be
 * hand-edited** — rerun the tool instead, so the SHA-256 in `PROVENANCE.txt` keeps
 * matching. [parse] is pure (no Android dependency) and now runs in Rust; [load] is
 * the only Android half, reading the bytes and handing the text across.
 */
class ComponentTable private constructor(internal val inner: RustComponentTable) {

    /** Number of entries parsed — every key in the asset. */
    val entryCount: Int get() = inner.entryCount().toInt()

    /**
     * Number of kanji in the table — the population the IDF is computed over, so that
     * a stray non-ideograph key (there is none in the shipped asset) cannot shift
     * every weight.
     */
    val kanjiCount: Int get() = inner.kanjiCount().toInt()

    /**
     * The components of [ch], or an empty list for a character the table has no entry
     * for. Never throws: an unknown character is simply no evidence, and every caller
     * in the proposal path (filter, majority vote, neighbours) treats an empty
     * decomposition as "this character contributes nothing".
     */
    fun componentsOf(ch: Char): List<Char> = inner.componentsOf(ch.code).map { Char(it) }

    /** Whether the table has an entry for [ch]. */
    fun hasComponents(ch: Char): Boolean = inner.hasComponents(ch.code)

    /**
     * Every kanji carrying **all** of [all] — the strict component filter the
     * deletion path measured at 229 -> 7 candidates with the right character surviving.
     *
     * Backed by the precomputed inverted index in Rust: the smallest posting list among
     * the requested components is filtered by the remaining ones, so the call is
     * proportional to the rarest component's set rather than to the whole table.
     *
     * Two deliberate choices, both mirroring the measured filter `comps and comps <=
     * set(table[c])` in `oov_component_probe.py`:
     *  - an **empty requirement returns nothing** (no evidence is not a licence to
     *    return all 12,156 kanji),
     *  - a component **no kanji carries** (unknown, or itself not a component) yields
     *    an empty result rather than being ignored.
     *
     * Result is ascending by codepoint and free of duplicates; [all] may repeat a
     * component without changing the result.
     */
    fun kanjiWith(all: List<Char>): List<Char> =
        inner.kanjiWith(all.map { it.code }).map { Char(it) }

    /**
     * `ln(kanjiCount / kanjiCountContaining(component))` — nats, not bits.
     *
     * A component carried by few kanji is strong evidence; `一` (most of the table)
     * is nearly worthless. An unknown component returns `0f`, mirroring the reference
     * `idf.get(c, 0.0)`: it adds no weight and can never make a fraction NaN.
     */
    fun idfOf(component: Char): Float = inner.idfOf(component.code)

    companion object {

        /** Path of the vendored table inside `src/main/assets`. */
        const val ASSET_PATH = "components/krad_components.txt"

        private val CACHE_LOCK = Any()

        @Volatile
        private var cached: ComponentTable? = null

        /**
         * Parse the table from its text form. Pure — no Android, no I/O — so unit
         * tests exercise the same code the device runs. Runs in Rust
         * (`ComponentTable::parse`), which is tolerant by design: a line without a
         * single-character key or with no parseable component is skipped rather than
         * crashing the app, because this parses a shipped asset. The unit test pinning
         * the entry count (12,156) is what makes a corrupted asset fail loudly.
         *
         * The **first** entry for a key wins, mirroring the generator's `setdefault`
         * in `tools/build_component_table.py`; components are de-duplicated within a
         * line, which is what the generator does too.
         */
        fun parse(text: String): ComponentTable = ComponentTable(RustComponentTable.parse(text))

        /**
         * The table from the bundled asset, parsed on first use and cached
         * process-wide (later calls are a volatile read).
         *
         * The asset is ~266 KB / 12,156 lines, so **call this off the main thread**
         * (a coroutine on `Dispatchers.IO`, or a worker) — the read and parse are the
         * only work in this class that touches the device.
         */
        fun load(context: Context): ComponentTable {
            cached?.let { return it }
            synchronized(CACHE_LOCK) {
                cached?.let { return it }
                val text = context.applicationContext.assets
                    .open(ASSET_PATH)
                    .use { it.readBytes().toString(Charsets.UTF_8) }
                return parse(text).also { cached = it }
            }
        }
    }
}
